name: Vitest Test

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: '0 22 * * *' # 每天早上6点触发 (UTC时间)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup pnpm
        run: |
          export PNPM_HOME="/home/runner/.local/share/pnpm"
          export PATH="$PNPM_HOME:$PATH"
          source /home/runner/.bashrc

      - name: Install dependencies
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh
          pnpm install

      - name: Run Vitest tests
        run: npm test
