name: Vitest Test

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: '0 22 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh
          export PATH="/usr/local/bin:$PATH"
          pnpm install

      - name: Run Vitest tests
        run: npm test
