name: Your Workflow Name

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *' # 每天早上6点触发 (UTC时间)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh
          source /home/runner/.bashrc

      - name: Install project dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

