name: Vitest Test

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: '0 22 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh
          source ~/.bashrc
        if: success()

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: pnpm install

      - name: Run Vitest tests
        run: pnpm test
